[package]
name = "libcryptsetup-rs"
version = "0.6.0"
authors = ["John Baublitz <jbaublitz@redhat.com>"]
edition = "2021"
rust-version = "1.62.1"  # LOWEST SUPPORTED RUST TOOLCHAIN
description = "High level Rust bindings for libcryptsetup"
license = "MPL-2.0"
documentation = "https://docs.rs/libcryptsetup-rs"
homepage = "https://stratis-storage.github.io/"
repository = "https://github.com/stratis-storage/libcryptsetup-rs"
build = "build.rs"
keywords = ["Linux", "encryption", "storage"]
categories = ["cryptography", "api-bindings", "os::linux-apis"]
exclude = [".clippy.toml", ".githooks/*", ".gitignore", ".github/*", "Makefile"]

[dependencies.libcryptsetup-rs-sys]
version = "0.2.0"
path = "./libcryptsetup-rs-sys"

[dependencies]
either = "1.6.1"
libc = "0.2.137"
bitflags = "1.3.2"
serde_json = "1.0.0"
lazy_static = "1.4.0"

[dependencies.uuid]
version = "1.0.0"
features = ["v4"]

[build-dependencies]
pkg-config = "0.3.7"
semver = "1.0.0"

[dev-dependencies]
base64 = "0.13.0"
loopdev = "0.4.0"
nix = "0.26.0"
rand = "0.8.0"

[features]
mutex = []
