[package]
name = "cryptsetup"
version = "0.1.0"
authors = ["John Baublitz <jbaublitz@redhat.com>"]
edition = "2018"

[dependencies.cryptsetup-sys]
version = "0.1.0"
path = "./cryptsetup-sys"

[dependencies]
libc = "0.2.60"
serde_json = "*"
uuid = "0.7.4"

[dev-dependencies]
base64 = "*"
loopdev = "*"
nix = "*"
rand = "*"
