[package]
name = "libcryptsetup-rs"
version = "0.1.0"
authors = ["John Baublitz <jbaublitz@redhat.com>"]
edition = "2018"

[dependencies.libcryptsetup-rs-sys]
version = "0.1.0"
path = "./cryptsetup-sys"

[dependencies]
either = "1.5"
libc = "0.2.60"
serde_json = "1.0"
uuid = "0.7.4"

[dev-dependencies]
base64 = "0.10"
loopdev = "0.2"
nix = "0.15"
rand = "0.7"
