---
name: libcryptsetup nightly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 10 3 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  allowed_failures:
    continue-on-error: true
    env:
      TASK: clippy
      TOOLCHAIN: stable
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          toolchain: ${{ env.TOOLCHAIN }}
          override: true
      - name: Install dependencies
        run: >
          sudo
          add-apt-repository
          "deb http://us.archive.ubuntu.com/ubuntu/ focal main"
      - name: Install dependencies
        run: sudo apt-get install libcryptsetup-dev
      - name: Test linting on ${{ env.TOOLCHAIN }} toolchain
        run: make -f Makefile $TASK

  checks-with-ci-repo:
    strategy:
      matrix:
        include:
          # yamllint disable rule:line-length
          - task: |
              COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../libcryptsetup-rs-sys/Cargo.toml FEDORA_RELEASE=rawhide make -f ../../Makefile check-fedora-versions
              COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../libcryptsetup-rs-sys/Cargo.toml FEDORA_RELEASE=f35 make -f ../../Makefile check-fedora-versions
              COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../Cargo.toml FEDORA_RELEASE=rawhide IGNORE_ARGS="--ignore-high=libcryptsetup-rs-sys" make -f ../../Makefile check-fedora-versions
              COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../Cargo.toml FEDORA_RELEASE=f35 IGNORE_ARGS="--ignore-high=libcryptsetup-rs-sys" make -f ../../Makefile check-fedora-versions
    runs-on: ubuntu-18.04
    container:
      image: fedora:36  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          clang
          cryptsetup-devel
          curl
          git
          make
          openssl-devel
          python-requests
          python-semantic_version
      - uses: actions-rs/toolchain@v1
        with:
          components: cargo
          toolchain: 1.63.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
          override: true
      - name: Check out ci repo
        run: git clone https://github.com/stratis-storage/ci.git
      - name: Run ${{ matrix.task }}
        run: ${{ matrix.task }}
        working-directory: ./ci/dependency_management
